version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/*"

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: weekly
